#!/usr/bin/env bash
#
# weekly-maintenance.sh — keep the wiki fresh without a 90-day cliff.
#
# Why: 154 of 177 pages were verified on the same two days, so they would all go stale on the
# same day. This runs weekly (cron), re-snapshots the sources, and queues ONLY the pages whose
# cited sources actually changed. It never pushes and never touches a dirty working tree.
#
# Steps: refetch official docs -> find changed raw/docs/official files -> map them to citing
# wiki pages -> fetch any new Claude Code changelog versions -> bump frozen pages -> reindex ->
# lint -> commit everything to a local branch maintenance/YYYY-MM-DD and return to the
# original branch. doctor.sh reports the queue and the unmerged branch at the next session.
#
# Usage: ./scripts/weekly-maintenance.sh            (installed in crontab by install-maintenance-cron.sh)
set -uo pipefail
cd "$(git rev-parse --show-toplevel)" || exit 1
TODAY=$(date +%F)
echo "=== weekly maintenance $TODAY ==="

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "working tree has uncommitted changes; skipping this week"; exit 0
fi
START_BRANCH=$(git branch --show-current)
BRANCH="maintenance/$TODAY"
git show-ref --quiet "refs/heads/$BRANCH" && { echo "$BRANCH already exists; skipping"; exit 0; }
git switch -q -c "$BRANCH" || exit 1
trap 'git switch -q "$START_BRANCH" 2>/dev/null' EXIT

if ! ls raw/docs/official/*.md >/dev/null 2>&1; then
  echo "no sources on disk; run ./scripts/sources.py fetch first"; exit 0
fi
./scripts/refetch-docs.sh >/dev/null 2>&1 || echo "refetch-docs.sh reported failures"
# raw/ is gitignored by default, so "changed" means "differs from the snapshot in sources/manifest.tsv
# that the wiki was last verified against". If raw/ is tracked in git, its diff counts as well.
CHANGED=$( { python3 scripts/sources.py changed --prefix raw/docs/official; git diff --name-only -- raw/docs/official 2>/dev/null; } | grep '\.md$' | sort -u || true)
./scripts/changelog-delta.sh || true
NEWLOG=$( { python3 scripts/sources.py new --prefix raw/docs/changelog-; git status --porcelain -- 'raw/docs/changelog-*' 2>/dev/null | awk '{print $2}'; } | sort -u)

{
  echo "# Re-verification queue — $TODAY"
  echo
  echo "Generated by scripts/weekly-maintenance.sh. Tick a page once it has been re-checked against the changed source."
  echo
  if [ -z "$CHANGED" ] && [ -z "$NEWLOG" ]; then echo "No cited source changed this week."; fi
  for f in $CHANGED; do
    for page in $(grep -rl -- "$f" wiki --include='*.md' 2>/dev/null); do
      echo "- [ ] \`$page\` — cites \`$f\` (changed)"
    done
  done | sort -u
  for f in $NEWLOG; do echo "- [ ] ingest \`$f\` into [[whats-new]] and the pages that own the changed features"; done
} > outputs/reverify-queue.md

./scripts/freshness.py --bump >/dev/null 2>&1 || true
[ -x .venv/bin/python ] && .venv/bin/python scripts/mem0/index_wiki.py >/dev/null 2>&1
SCORE=$(./scripts/wiki-lint.sh --json 2>/dev/null | grep -m1 '"health_score"' | grep -oE '[0-9]+')
QN=$(grep -c '^- \[ \]' outputs/reverify-queue.md || true)

git add -A raw wiki outputs/reverify-queue.md || { echo "git add failed (is a staged path gitignored?)" >&2; exit 1; }
if git diff --cached --quiet; then
  echo "nothing changed"; git switch -q "$START_BRANCH"; git branch -q -D "$BRANCH"; trap - EXIT; exit 0
fi
git commit -q -m "Weekly maintenance $TODAY: $(echo "$CHANGED" | grep -c . || true) official page(s) changed, ${QN:-0} item(s) queued, lint ${SCORE:-?}"
echo "committed to $BRANCH; queue: ${QN:-0} item(s); lint ${SCORE:-?}"
