#!/usr/bin/env python3
"""Generate the Codex and OpenCode configuration from the Claude Code originals.

Source of truth                      Generated
  .claude/agents/<name>.md      ->   .opencode/agents/<name>.md, .codex/agents/<name>.toml
  .mcp.json                     ->   opencode.json (mcp), .codex/config.toml ([mcp_servers.*])
  .claude/skills/*/SKILL.md     ->   opencode.json (permission.skill: "ask" for skills that set
                                     disable-model-invocation, which only Claude Code understands)
  (this file)                   ->   .codex/hooks.json

Why generate: four agents read four formats, and hand-maintained copies drift. Edit the Claude Code
file, run this, commit both. `--check` exits 1 when anything is stale (tests/test_agent_sync.py).
Instructions and skills need no generation: AGENTS.md and .agents/skills are symlinks.
Hermes keeps its configuration per user, not per project: see scripts/agents/hermes/setup.sh.
Standard library only.
"""
import glob
import json
import os
import shlex
import sys

REPO = os.path.realpath(os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", ".."))
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}
WEB_TOOLS = {"WebFetch", "WebSearch"}
# Every command resolves the repository itself: Codex runs MCP servers and hooks from wherever it was
# started, which may be a subdirectory, and a committed file cannot carry an absolute path.
ROOT = '"$(git rev-parse --show-toplevel)"'


def frontmatter(path):
    text = open(path, encoding="utf-8").read()
    _, fm, body = text.split("---", 2)
    meta = {}
    for line in fm.strip().splitlines():
        if ":" in line and not line.startswith((" ", "#")):
            k, v = line.split(":", 1)
            v = v.strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
                v = v[1:-1]
            meta[k.strip()] = v
    return meta, body.strip() + "\n"


def launcher(server):
    argv = [server["command"]] + list(server.get("args") or [])
    return f"cd {ROOT} && exec " + " ".join(shlex.quote(a) for a in argv)


def toml_str(s):
    return json.dumps(s, ensure_ascii=False)  # a JSON string is a valid TOML basic string


def build():
    out = {}
    servers = json.load(open(os.path.join(REPO, ".mcp.json"), encoding="utf-8"))["mcpServers"]

    for path in sorted(glob.glob(os.path.join(REPO, ".claude", "agents", "*.md"))):
        meta, body = frontmatter(path)
        name = meta["name"]
        tools = {t.strip() for t in meta.get("tools", "").split(",") if t.strip()}
        read_only = bool(tools) and not (tools & WRITE_TOOLS)
        no_web = bool(tools) and not (tools & WEB_TOOLS)
        note = f"Generated by scripts/agents/sync.py from .claude/agents/{name}.md. Edit that file, then rerun."

        deny = (["edit"] if read_only else []) + (["webfetch", "websearch"] if no_web else [])
        lines = ["---", f"description: {json.dumps(meta['description'], ensure_ascii=False)}", "mode: subagent"]
        if deny:
            lines += ["permission:"] + [f"  {d}: deny" for d in deny]
        lines += ["---", "", f"<!-- {note} -->", "", body]
        out[f".opencode/agents/{name}.md"] = "\n".join(lines)

        codex = [f"# {note}", f"name = {toml_str(name)}", f"description = {toml_str(meta['description'])}"]
        if read_only:
            codex.append('sandbox_mode = "read-only"')
        codex.append(f"developer_instructions = {toml_str(body)}")
        out[f".codex/agents/{name}.toml"] = "\n".join(codex) + "\n"

    ask_first = {}
    for path in sorted(glob.glob(os.path.join(REPO, ".claude", "skills", "*", "SKILL.md"))):
        meta, _ = frontmatter(path)
        if meta.get("disable-model-invocation", "").lower() == "true":
            ask_first[meta["name"]] = "ask"
    opencode = {
        "$schema": "https://opencode.ai/config.json",
        "mcp": {n: {"type": "local", "command": ["bash", "-c", launcher(s)], "enabled": True, "timeout": 60000}
                for n, s in servers.items()},
        "permission": {"skill": {"*": "allow", **ask_first}},
    }
    out["opencode.json"] = json.dumps(opencode, indent=2, ensure_ascii=False) + "\n"

    toml = ["# Generated by scripts/agents/sync.py from .mcp.json. Edit that file, then rerun.",
            "# Codex loads this only after you trust the project, and its hooks (.codex/hooks.json) only",
            "# after you review them once with /hooks.", ""]
    for n, s in servers.items():
        toml += [f"[mcp_servers.{n}]", 'command = "bash"', f"args = [\"-c\", {toml_str(launcher(s))}]",
                 "startup_timeout_sec = 60", ""]
    out[".codex/config.toml"] = "\n".join(toml)

    def cmd(interp, rel, *args):
        return " ".join([interp, f"{ROOT[:-1]}/{rel}\""] + list(args))

    hooks = {"hooks": {
        "SessionStart": [{"matcher": "startup|resume", "hooks": [
            {"type": "command", "command": cmd("bash", "scripts/hooks/session-start.sh"), "timeout": 30}]}],
        "PreToolUse": [{"matcher": "^apply_patch$", "hooks": [
            {"type": "command", "command": cmd("python3", "scripts/agents/adapter.py", "guard"),
             "timeout": 10, "statusMessage": "Checking raw/ sources"}]}],
        "Stop": [{"hooks": [
            {"type": "command", "command": cmd("bash", "scripts/hooks/stop-anti-evaporation.sh"), "timeout": 10}]}],
        "SessionEnd": [{"hooks": [
            {"type": "command", "command": cmd("bash", "scripts/hooks/session-end.sh"), "timeout": 3}]}],
    }}
    out[".codex/hooks.json"] = json.dumps(hooks, indent=2) + "\n"
    return out


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, content in build().items():
        path = os.path.join(REPO, rel)
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != content:
            stale.append(rel)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
    verb = "stale" if check else "wrote"
    print("\n".join(f"{verb}: {r}" for r in stale) if stale else "agent configs are up to date")
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
